name: Test

on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm run test
